# -*- mode: ruby -*-
# vi: set ft=ruby :

$out_file = File.new('debug.log', 'w')
def $stdout.write string
    log_datas=string
    if log_datas.gsub(/\r?\n/, "") != ''
        log_datas=::Time.now.strftime("[%Y-%m-%d %T %z]")+" "+log_datas.gsub(/\r\n/, "\n")
    end
    super log_datas
    $out_file.write log_datas
    $out_file.flush
end
def $stderr.write string
    log_datas=string
    if log_datas.gsub(/\r?\n/, "") != ''
        log_datas=::Time.now.strftime("[%Y-%m-%d %T %z]")+" "+log_datas.gsub(/\r\n/, "\n")
    end
    super log_datas
    $out_file.write log_datas
    $out_file.flush
end

require 'json'

boxes = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'boxes.json')))

Vagrant.configure("2") do |config|
    boxes.drop(1).each do |box|
        config.ssh.insert_key = false
        config.ssh.forward_agent = true

        config.vm.define box['name'] do |curr|
            curr.vm.box = box['box']

            curr.vm.network "private_network", ip: box['ip']

            curr.vm.provider "virtualbox" do |vb|
                vb.name = box['name']
                # Display the VirtualBox GUI when booting the machine
                vb.gui = false
                # Customize the amount of memory on the VM:
                vb.memory = box['memory']
                vb.cpus = box['cpus']
                # make it usable from WSL:
                vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
            end

            curr.vm.provision "ansible" do |ansible|
                ansible.playbook = box['playbook']
                #ansible.verbose = "vvvv"
                ansible.extra_vars = {
                    registry_ip: box['registry_ip'],
                    database_ip: box['database_ip'],
                    monitoring_ip: box['monitoring_ip']
                }
            end
        end
    end
end