---
groups:

  - name: default
    rules:
      - alert: CPU_Rate
        expr: system_cpu_usage > 0.01
        labels:
          severity: high
        annotations:
          summary: WARN ! CPU High

      - alert: apps_down
        expr: up{job=~"apps"}==0
        labels:
          severity: major
        annotations:
          description: Service {{ $labels.instance }} is unavailable.
          value: DOWN ({{ $value }})
