---
# global config
global:
  scrape_interval: 15s
  evaluation_interval: 5s
  scrape_timeout: 5s
  # query_log_file: <string>
  external_labels:
    monitor: 'codelab-monitor'

# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5s
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: 'apps'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'app1:80'
          - 'app2:80'

rule_files:
  - "prometheus-alerts.yml"
