---
- hosts: lb
  become: true
  pre_tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

  roles:
    - geerlingguy.docker

  tasks:
    - name: install python dependencies
      become: true
      apt:
        update_cache: yes
        state: latest
        name: python3-pip

    - name: install 'Docker SDK for Python'
      # become: true  # WILL STOP WORKING IF UNCOMMENTED
      pip:
        name: docker

    - name: add vagrant user to docker group
      user:
        name: vagrant
        append: yes
        groups: docker
      become: true

    - name: add app ip addresses to nginx configuration
      run_once: true
      blockinfile:
        path: /vagrant/balancer/nginx.conf
        insertafter: "upstream app {"
        marker: "        # {mark} ANSIBLE MANAGED BLOCK {{item}}"
        block: "        server {{ hostvars[item].ansible_host }};"
      when: hostvars[item].inventory_hostname is match("app*")
      with_items: "{{ groups.app }}"

    - name: run nginx container
      docker_container:
        name: nginx-lb
        state: started
        restart_policy: unless-stopped
        image: nginx:1.21.6-alpine
        # pull: true
        ports:
          - "80:80"
        volumes:
          - /vagrant/balancer/nginx.conf:/etc/nginx/nginx.conf
          - /vagrant/balancer/logs:/etc/nginx/logs
          - /vagrant/balancer/html:/var/www/html
    
    - name: run filebeat collector
      docker_container:
        user: root
        name: filebeat
        state: started
        restart_policy: unless-stopped
        image: docker.elastic.co/beats/filebeat:8.1.2
        pull: true
        etc_hosts: >
          { "monitoring": "{{monitoring_ip}}" }
        volumes:
          - /vagrant/monitoring/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
          - /var/lib/docker/containers:/var/lib/docker/containers:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro
        command: "filebeat -e --strict.perms=false -E output.elasticsearch.hosts=[\"monitoring:9200\"]"
