---
- hosts: default
  become: true
  pre_tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes
        cache_valid_time: 86400 # invalidate cache in 1 day
      when: ansible_os_family=='Debian'

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: add vagrant user to docker group
      user:
        name: vagrant
        append: yes
        groups: docker
      become: true