---
- hosts: monitoring
  become: true
  pre_tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

  vars:
    elk_git: https://github.com/deviantony/docker-elk.git
    elk_path: /usr/local/src/docker-elk

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: install python dependencies
      become: true
      apt:
        update_cache: yes
        state: latest
        name: python3-pip

    - name: install 'Docker SDK for Python'
      # become: true  # WILL STOP WORKING IF UNCOMMENTED
      pip:
        name:
          - docker
          - docker-compose

    - name: add vagrant user to docker group
      user:
        name: vagrant
        append: yes
        groups: docker
      become: true

    - name: get elk
      git:
        repo: "{{ elk_git }}"
        dest: "{{ elk_path }}"

    - name: start elk services
      docker_compose:
        project_src: "{{ elk_path }}"
      register: output

    - debug:
        var: output

    - name: run prometheus container
      docker_container:
        user: root
        name: prometheus
        state: started
        restart_policy: unless-stopped
        image: prom/prometheus:v2.35.0
        pull: true
        etc_hosts: >
          {
            "app1": "{{app1_ip}}",
            "app2": "{{app2_ip}}"
          }
        ports:
          - "9090:9090"
        volumes:
          - /vagrant/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
          - /vagrant/monitoring/prometheus-alerts.yml:/etc/prometheus/prometheus-alerts.yml:ro
