---
- hosts: app1,app2
  become: true
  pre_tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

  roles:
    - geerlingguy.docker

  tasks:
    - name: install python dependencies
      become: true
      apt:
        update_cache: yes
        state: latest
        name: python3-pip

    - name: install 'Docker SDK for Python'
      #become: true  # WILL STOP WORKING IF UNCOMMENTED
      pip:
        name: docker

    - name: add vagrant user to docker group
      user:
        name: vagrant
        append: yes
        groups: docker
      become: true

    - name: remove daemon.json file
      file:
        path: /etc/docker/daemon.json
        state: absent
    - name: ensure daemon.json file exists
      file:
        path: /etc/docker/daemon.json
        state: touch
    - name: add local ip address to allowed insecure hosts
      lineinfile:
        path: /etc/docker/daemon.json
        state: present
        line: "{{ item.value | to_nice_json }}"
      with_items:
        - value: "{\"insecure-registries\":[\"{{registry_ip}}:5000\"],\"log-driver\":\"json-file\"}"
    - name: docker restart
      service:
        name: docker
        state: restarted

    - name: run app container
      docker_container:
        name: "petclinic-{{inventory_hostname}}"
        state: started
        restart_policy: unless-stopped
        image: "{{registry_ip}}:5000/petclinic:latest"
        pull: true
        ports:
          - "80:8080"
        etc_hosts:
          "db": "{{database_ip}}"

    - name: run filebeat collector
      docker_container:
        user: root
        name: filebeat
        state: started
        restart_policy: unless-stopped
        image: docker.elastic.co/beats/filebeat:8.1.2
        pull: true
        etc_hosts: >
          { "monitoring": "{{monitoring_ip}}" }
        volumes:
          - /vagrant/monitoring/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
          - /var/lib/docker/containers:/var/lib/docker/containers:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro
        command: "filebeat -e --strict.perms=false -E output.elasticsearch.hosts=[\"monitoring:9200\"]"
