---
- hosts: db
  become: true
  pre_tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

  roles:
    - geerlingguy.docker

  tasks:
    - name: install python dependencies
      become: true
      apt:
        update_cache: yes
        state: latest
        name: python3-pip

    - name: install 'Docker SDK for Python'
      # become: true  # WILL STOP WORKING IF UNCOMMENTED
      pip:
        name: docker

    - name: "run container"
      docker_container:
        name: petclinic-db
        state: started
        restart_policy: unless-stopped
        image: postgres:alpine3.15
        pull: true
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: petclinic
          POSTGRES_PASSWORD: petclinic
          POSTGRES_DB: petclinic
        command: "postgres -c log_statement=all -c log_destination=stderr"

    - name: run filebeat collector
      docker_container:
        user: root
        name: filebeat
        state: started
        restart_policy: unless-stopped
        image: docker.elastic.co/beats/filebeat:8.1.2
        pull: true
        etc_hosts: >
          { "monitoring": "{{monitoring_ip}}" }
        volumes:
          - /vagrant/monitoring/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
          - /var/lib/docker/containers:/var/lib/docker/containers:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro
        command: "filebeat -e --strict.perms=false -E output.elasticsearch.hosts=[\"monitoring:9200\"]"
